# Generated by Django 4.2.6 on 2023-10-18 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug_History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactions.drug')),
            ],
        ),
    ]
